/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.up = function (knex) {
  return knex.schema.createTable('regions', function (table) {
    table.increments('id') //makes unique id field an populates it with an autogenerated incrementing number
    table.string('region_name') //short field
  })
}

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.down = function (knex) {
  return knex.schema.dropTable('regions')
}
